# Generated by Django 4.1.5 on 2023-02-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADD_TO_CART', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_to_cart',
            name='cart_qty',
            field=models.IntegerField(default=1),
        ),
    ]
