# Generated by Django 4.1.5 on 2023-02-07 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AUTHENTICTION', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_registration',
        ),
    ]
