# Generated by Django 4.1.5 on 2023-02-06 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PRODUCT', '0001_initial'),
        ('ORDERS', '0002_rename_order_details_rename_cust_id_details_cust_id'),
        ('DASHBOARD', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay_details',
            fields=[
                ('pay_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pay_type', models.CharField(max_length=100)),
                ('pay_upiId', models.CharField(max_length=100)),
                ('pay_NameOnCard', models.CharField(max_length=100)),
                ('pay_CardNum', models.IntegerField()),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DASHBOARD.customer_details')),
                ('o_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORDERS.details')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRODUCT.p_details')),
            ],
        ),
    ]
