# Generated by Django 4.1.5 on 2023-02-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p_details',
            name='p_img',
            field=models.ImageField(upload_to='Products'),
        ),
    ]
