# Generated by Django 4.1.5 on 2023-02-07 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DASHBOARD', '0001_initial'),
        ('PRODUCT', '0003_p_details_p_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_to_cart',
            fields=[
                ('cart_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cart_qty', models.IntegerField(default=1)),
                ('cust_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='DASHBOARD.customer_details')),
                ('p_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='PRODUCT.p_details')),
            ],
        ),
    ]
