# Generated by Django 4.1.5 on 2023-02-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_details',
            fields=[
                ('cust_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cust_name', models.CharField(max_length=50)),
                ('cust_surname', models.CharField(max_length=50)),
                ('cust_phoneno', models.IntegerField()),
                ('cust_address1', models.CharField(max_length=150)),
                ('cust_address2', models.CharField(max_length=150)),
                ('cust_postcode', models.IntegerField()),
                ('cust_area', models.CharField(max_length=50)),
                ('cust_emailid', models.EmailField(max_length=50)),
                ('cust_country', models.CharField(max_length=50)),
                ('cust_state', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery_details',
            fields=[
                ('del_id', models.IntegerField(primary_key=True, serialize=False)),
                ('del_name', models.CharField(max_length=50)),
                ('del_surname', models.CharField(max_length=50)),
                ('del_phoneno', models.IntegerField()),
                ('del_address1', models.CharField(max_length=150)),
                ('del_address2', models.CharField(max_length=150)),
                ('del_postcode', models.IntegerField()),
                ('del_area', models.CharField(max_length=50)),
                ('del_emailid', models.EmailField(max_length=50)),
                ('del_country', models.CharField(max_length=50)),
                ('del_state', models.CharField(max_length=20)),
                ('del_adharno', models.IntegerField()),
            ],
        ),
    ]
