# Generated by Django 4.1.5 on 2023-02-06 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCT', '0001_initial'),
        ('DASHBOARD', '0001_initial'),
        ('ORDERS', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='order',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='cusT_id',
            new_name='cust_id',
        ),
    ]
